### ISSUE TITLE
Baza danych - min 4 tabele

### ISSUE THREAD

**Issue by mnatan** [mnatan/PSI-2#2]
Min. 4 tabele (wliczając tabelę użytkowników) z których każda jest połączona relacją inną niż 1-1 z jakąś inną tabelą. 
Dla każdej tabeli powinna być akcja w ramach aplikacji która jakoś modyfikuje jej zawartość (usuwa, zmienia, dodaje rekordy).

mniejsza ilość tabel oznacza -7 punktów za każdą tabelę mniej - do tej puli nie będą wliczane tabele które mogłyby być zamienione na typy wyliczeniowe,

**Comment by s-nez** [comment]
Zrobione przez DJango.
